name: "LLM Code Style Reviewer"
description: "Hybrid Static + LLM-based Code Style Reviewer for Java files"
author: "Varun"

inputs:
  openai_api_key:
    description: "OpenAI API Key"
    required: false
  base_branch:
    description: "Base branch to diff against"
    required: false
    default: "main"

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    BASE_BRANCH: ${{ inputs.base_branch }}
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
