name: "LLM Code Style Reviewer"
description: "Hybrid Static + LLM-based Code Style Reviewer for Java files"
author: "Varun"

inputs:
  openai_api_key:
    description: "OpenAI API Key"
    required: false
  gemini_api_key:
    description: "Gemini API Key"
    required: false
  claude_api_key:
    description: "Claude API Key"
    required: false
  base_branch:
    description: "Base branch to diff against"
    required: false
    default: "main"

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
    CLAUDE_API_KEY: ${{ inputs.claude_api_key }}
